### ISSUE TITLE
Create Google sheet smart chip work request

### ISSUE THREAD

**Issue by saumier** [culturecreates/artsdata-data-model#111]
Work order created:
https://docs.google.com/document/d/16esBj2X5tm4gW7x6C1xNli8ngdzJvpEliQcoia8zYyE/edit?usp=sharinghttps://docs.google.com/document/d/16esBj2X5tm4gW7x6C1xNli8ngdzJvpEliQcoia8zYyE/edit?usp=sharing

**Comment by saumier** [comment]
Here is the original email with the idea:

Salut Frédéric,

The bi-weekly yesterday made me think about a prototype of an event spreadsheet that could use Artsdata K-numbers for places and performers, organizers, event types, etc. instead of having to enter them manually.

The idea is to have a minimal template that would use smart chips so the user could roll over cells to see the full details from Artsdata. 

Here is a Google sheet but without the smart chip (not built yet). But is you roll over the Main Webpage URL cell you can get an idea of a smart chip.
https://docs.google.com/spreadsheets/d/1MY-6ckSH34Olw3hwKrJDSg7kbYlGinmDr5aRP6cvp2o/edit?usp=sharing

This proptype would develop 2 smart chip features of Google sheets:
1. [preview-links](https://developers.google.com/apps-script/add-ons/editors/gsao/preview-links) - to make a card appear when you roll over the K-number to display the name and details from Artsdata.
2. Lookup - to enable a person to type a name of a place or person/organization into the cell and have it reconciile with Artsdata by showing a card with a list of matches to select.  This would add the K-number to the spreadsheet.

This is the user flow:
1. open any new Google sheet
2. Add the "Artsdata smart chip" as an extension to your user account from Google market place.
3. From the Artsdata extension menu in Google sheets, select "create new events tab" (this opens a new tab with the standard column headers already added)
4. Enter you event data (for example in the performer cell start by typing the name of the performer and then selecting a match from the list from the smart chip)
5. Review your work (roll over K-numbers to see the full details in the smart chip)
5. From the Artsdata extension menu in Google sheets, select "login to Artsata" to login using your GitHub account
6. Enter a name for the artifact.
6. Click the "push to Artsdata" button

The events would be uploaded via the Artsdata Databus and minted (or linked) to an existing entity in Artsdata. The Artsdata K-numbers would be automatically added back to the spreadsheet as read-only.

If you need to create a new place or person/organization you could follow similar steps in a different tab. Like "create new places tab".

This protoytpe could be discussed in our next bi-weekly and if you think it is worth making it into a Work Order then I could assign one of my team members to make the "Artsdata smart chip" extension and we could test it out.  One advantage of this approach is that the spreadsheet has very little code and therefore very little to maintain. 

Regards,
Gregory

**Comment by saumier** [comment]
Work order to review
https://docs.google.com/document/d/16esBj2X5tm4gW7x6C1xNli8ngdzJvpEliQcoia8zYyE/edit?usp=sharing


> Bonjour Gregory,
> I heard you've been away supporting your mother in Mexico. I hope everything is ok on this front.
> Since you could not attend today's bi-weekly meeting and discuss the merits of developing two Google Sheet prototypes concurrently, I made the decision of moving ahead with both.
> Here's a work request for your proposed Google Sheet with smart chips:
https://docs.google.com/document/d/16esBj2X5tm4gW7x6C1xNli8ngdzJvpEliQcoia8zYyE/edit?usp=sharing
> Please note that A10s committed to a tight timeline in order to deliver Dessa with an MVP that she could promote at her ArtsReach workshop, on June 25. Would this timeline be feasible for Culture Creates?

**Comment by saumier** [comment]
@tammy-culture @troughc   Please review the work order that I assigned to Fred incase you see any issues I missed. I think Suhail and Dev can do most of this work. 
https://docs.google.com/document/d/16esBj2X5tm4gW7x6C1xNli8ngdzJvpEliQcoia8zYyE/edit

**Comment by tammy-culture** [comment]
@saumier I made some adjustments to the payment schedule. Looks good.

**Comment by fjjulien** [comment]
@saumier Here's a question and concern regarding the user flow:

**What would the user be expected to do if their location, organizer or performer entity does not exist in Artsdata yet?**

In your initial email, you wrote: "If you need to create a new place or person/organization you could follow similar steps in a different tab. Like "create new places tab"." However, this feature is not included in the quote.

I'm not convinced it would be a good idea to invite users to create 'permanent' entities (as opposed to ephemeral events) into a Google Sheet. 

- Data providers tend to be careless when populating any form. They might be even more careless if asked to do it in a Google Sheet (rather than a more formal looking user interface).
- In a user interface, we have a access to a range of tools to gently guide the user towards the expected behaviour: field label, field instruction, placeholder text, tooltips, etc. In a Google Sheet, we would have just a column label.
- Creating person and organization records that can be clearly disambiguated requires more than typing a name and an address. It also requires other kinds of information that may seem overkill and that a user may not be willing to provide (business number, legal name, person occupation, person work location).

If the goal of this tool is to generate data that Artsdata data consumers can reuse, it might be best not to ask users to create their own organization and person records. Places, perhaps. But for organizations and persons, I would bring in people like Dessa and Dorian to assist with the creation of records.

**Comment by saumier** [comment]
> What would the user be expected to do if their location, organizer or performer entity does not exist in Artsdata yet?

@fjjulien For this project I agree to leave out the creation of new orgs and people.  For the beta we ask people to only choose from existing places, people, orgs. Since place is mandatory, this will work well for events in a single venue and presenters that always perform in the same set of venues. In the roll-out phase, I can imagine feedback from users that may have multiple locations that need to be added. If needed we could add 6 place/address properties so that nested places with blank nodes are possible.

**Comment by fjjulien** [comment]
@saumier As discussed at the [bi-weekly meeting](https://docs.google.com/document/d/1W_1a9kDGJ8VaNn0y5iKK0TUl68c7G8ffFHkcU5fhOhI/edit?usp=sharing), please consider a workflow for loading the JSON-LD from the [MVP developed by A10s](https://docs.google.com/spreadsheets/d/1XnO3Gj7X0CunDOWUWFNI8HshW2vq2yvCLsTPpqvIDFU/edit?usp=sharing).
