### ISSUE TITLE
SuperEvent type and series of performances

### ISSUE THREAD

**Issue by fjjulien** [culturecreates/artsdata-data-model#56]
In the current structured data read me file, we are instructing users to describe series of performances thusly:
"If your event has a series of performances of the same show, please add the Event Series template to the Event template to describe each individual performance as a [‘subEvent’](https://schema.org/subEvent), and then change the top Event type to [‘EventSeries’](https://schema.org/EventSeries).

Question 1. Will this strategy work well in cases where a series of performances is presented as part of a larger series? For example, Festival Transamériques regularly presents series of theatre performances. Or else, the National Arts Centre presents series of dance performances as part its dance series. Under the current model, both the series of theatre performances and the super series (or festival) and the could have the type "EventSeries". This isn't conceptually wrong, although it may cause some confusion.

Question 2. If the template is adopted only by a few users, then we will end up collecting inconsistent structured data about series of performances. Most would have the type "event" and only a few adopters would have the type "EventSeries". This may have a negative impact on data reusability.

The scope notes for [schema:EventSeries](https://schema.org/EventSeries) suggest: "In general an EventSeries may seem more Event-like when the period of time is compact and when aspects such as location are fixed." Considering this note and the above issues, I would be in favour of instructing template users to keep the type "Event" for series of performances in the same location (rather than changing it to "EventSeries").

**Comment by saumier** [comment]
@fjjulien Using EventSeries is an extra indication that we are talking about a series and not a single event. However, an EventSeries is a subclass of Event, meaning that a search for Events will return all events including EventSeries. An EventSeries is also an Event.

For larger series, I do not see any confusion if a festival wants to use schema:EventSeries, but I would recommend a festival like FTA use schema:Festival which is also a subclass of Event.  

If people don't follow the template and use Event instead of EventSeries, I don't see that as a problem for reusability. In the wild there are already uses of both. I think "event series" makes intuitive sense for people in the performing arts that have multiple events with tickets, at least more sense that calling multiple events on different days an "event".

**Comment by fjjulien** [comment]
@saumier I had indeed noted that EventSeries is a subclass of Event, which I find very reassuring. I've been sitting on the fence, not entirely sure if I preferred one type or the other to describe "series of performances". On the one hand, using just the Event type is simpler; on the other hand, EventSeries is quite intuitive (as you pointed out). There are pros and cons to each and both enable to query all events. I'm comfortable either way. We can keep the template as is, with the recommendation to use the EventSeries type for series of performances.
